services:
  test:
    build: .
    command: sh -c "yarn install && yarn test"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres/postgres
      PAYLOAD_HOST: "0.0.0.0"
      PAYLOAD_PORT: 3000
    cap_add:
      - SYS_ADMIN
    ports:
      - 3000:3000
      - 3001:3001

  postgres:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  node_modules:
  pgdata:
